name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set version
        uses: redis-field-engineering/redis-version-action@v1
        with:
          version: ${{ github.event.inputs.version }}

      - name: Release
        uses: redis-field-engineering/redis-release-action@v1
        with:
          gpg-key-id: ${{ secrets.GPG_KEY_ID }}
          gpg-public-key: ${{ secrets.GPG_PUBLIC_KEY }}
          gpg-secret-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          sonatype-username: ${{ secrets.SONATYPE_USERNAME }}
          sonatype-password: ${{ secrets.SONATYPE_PASSWORD }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload test reports
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: |
            build/reports/aggregate-tests/
