name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Version
        run: |
          echo ${{ github.event.inputs.version }} > VERSION

      - name: Release
        uses: redis-field-engineering/redis-release-action@v2
        with:
          gpg-key-id: ${{ secrets.GPG_KEY_ID }}
          gpg-public-key: ${{ secrets.GPG_PUBLIC_KEY }}
          gpg-secret-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          sonatype-username: ${{ secrets.SONATYPE_USERNAME }}
          sonatype-password: ${{ secrets.SONATYPE_PASSWORD }}
          github-token: ${{ secrets.GIT_ACCESS_TOKEN }}

      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties

      - name: Upload test reports
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: |
            build/reports/aggregate-tests/

      - name: Set Version
        uses: redis-field-engineering/redis-version-action@v2
        with:
          version: ${{ github.event.inputs.version }}
